### ISSUE TITLE
uk government department for education openshift team would like to know more

### ISSUE THREAD

**Issue by simbo1905** [Skatteetaten/aurora-openshift#1]
Apologies for using a github issue to contact you. I am starting to write a uk government team tool like "Skatteetaten/ao" and your yoeman generator and I just found your pages at https://skatteetaten.github.io/aurora-openshift/. 

We are just about to start our beta build of our digital platform on openshift at the uk department for education. I am hoping our technical architect, lead programmer and openshift service manager could possibly speak with your team to learn more and discuss possible collaboration on opensource tools?

My email address is simon dot massey at education dot gov dot uk. Thanks!

**Comment by arevatte** [comment]
Hi Simon,

Thanks for contacting us! 
 
We would gladly speak to your team. I'll send you an email later on this weekend. 

All the best!
